# Generated by Django 4.1.3 on 2022-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="defaults/companylogo/default.jpg",
                null=True,
                upload_to="jobs/companylogos",
            ),
        ),
    ]
