# Generated by Django 4.1.3 on 2022-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="last_date",
            field=models.DateField(),
        ),
    ]
