# Generated by Django 4.1.3 on 2022-11-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
