# Generated by Django 4.0.8 on 2022-11-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/blogs/default.jpg', null=True, upload_to='jobs/companylogos'),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
