# Generated by Django 4.0.8 on 2022-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_form_link_job_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Link',
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Your google form link', max_length=100, null=True),
        ),
    ]
