# Generated by Django 4.0.8 on 2022-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_link_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Your google form link', max_length=500, null=True),
        ),
    ]
