# Generated by Django 4.0.8 on 2022-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='/hirethemv2/static/defaults/blogs/default.jpg', null=True, upload_to='jobs/companylogos'),
        ),
    ]
