# Generated by Django 4.0.8 on 2022-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='defaults/rooms/defaults.webp', upload_to='room/photos'),
        ),
    ]
