# Generated by Django 4.0.8 on 2022-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_options_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='defaults/rooms/defaults.webp', upload_to='room/photos/'),
        ),
    ]
