# Generated by Django 4.0.8 on 2022-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defaults/blog/default.jpg', null=True, upload_to='photos/profiles'),
        ),
    ]
