# Generated by Django 4.0.8 on 2022-11-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Enter your address in format - your state, your country', null=True, verbose_name='Your State and Country'),
        ),
    ]
