# Generated by Django 4.0.8 on 2022-11-24 07:27

from django.db import migrations, models
import hirethemv2.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/profiles/defaults.jpg', null=True, upload_to='photos/profiles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, help_text='Requires a ` pdf ` format of your resume.', null=True, upload_to='resumes/pdf/', validators=[hirethemv2.users.validators.validate_file_extension]),
        ),
    ]
