# Generated by Django 4.0.8 on 2022-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_address_alter_user_bio_alter_user_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='defaults/profiles/default.jpg', max_length=255, upload_to='photos/profiles'),
        ),
    ]
