# Generated by Django 4.0.8 on 2022-11-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/profiles/default.jpg', max_length=255, null=True, upload_to='photos/profiles/'),
        ),
    ]
