# Generated by Django 4.0.8 on 2022-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/hirethemv2/static/defaults/profiles/default.jpg', max_length=255, null=True, upload_to='photos/profiles/'),
        ),
    ]
